### ISSUE TITLE
QueryCrumbs history missing profile attribute

### ISSUE THREAD

**Issue by schloett** [EEXCESS/visualization-widgets#24]
Sometimes, querycrumbs fail due to a missing `profile` attribute. However, I could not yet figure out, when exactly this occurs / how to reproduce the error.

**Comment by mgrani** [comment]
happens for me to. Exception:

```
 Error in response to storage.get: TypeError: Cannot read property 'profile' of null
at Object.self.CORE.getQueryTerms (eval at <anonymous> (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/requireContent.js:1:0), <anonymous>:318:42)
at Object.self.CORE.generateVisualNode (eval at <anonymous> (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/requireContent.js:1:0), <anonymous>:168:41)
at Object.self.CORE.addVisualNode (eval at <anonymous> (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/requireContent.js:1:0), <anonymous>:327:48)
at eval (eval at <anonymous> (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/requireContent.js:1:0), <anonymous>:578:31)
at Object.callback (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/content.js:142:37)
at Object.searchBar.init.queryCrumbs.storage.getHistory [as getHistoryCallback] (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/content.js:141:54)
at Object.refresh (eval at <anonymous> (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/requireContent.js:1:0), <anonymous>:565:18)
at Object.refreshQC (eval at <anonymous> (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/requireContent.js:1:0), <anonymous>:658:20)
at qcRefresh (chrome-extension://gieldaokbpofcmgipcgoejicflmfnhmc/js/content.js:29:27)
```

**Comment by mgrani** [comment]
After digging deeper: The query object provided to addVisualNode is Null. i guess some unfinished query has been pushed to the query crumb history?

**Comment by schloett** [comment]
seemed to be a problem of storage handling in the chrome extension, therefore closing this issue and referencing https://github.com/EEXCESS/chrome-extension/issues/49.
